import asyncio, sys, json
from playwright.async_api import async_playwright
WS = '/tmp/claude-0/-home-user-rollmodel/5c52352e-692f-5301-ac55-ec4d2c708f3e/scratchpad/ws'
async def main(w, h, tag):
    async with async_playwright() as p:
        b = await p.chromium.launch(args=['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist'])
        ctx = await b.new_context(viewport={'width': w, 'height': h}, device_scale_factor=1, has_touch=True, is_mobile=True)
        await ctx.add_init_script("window.__tut = true; try { localStorage.setItem('paint-world-red.v1', JSON.stringify({ orient:'" + ('land' if w > h else 'port') + "', name:'Dusk', seen:{}, drops: 0 })); } catch (e) {}")
        pg = await ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)[:300]))
        shots = []
        async def shot(name): await pg.screenshot(path=f'{WS}/ui/tut_{tag}_{name}.png'); shots.append(name)
        async def tip(): return await pg.evaluate("[__T.tutPh(), __T.tut && __T.tut.step, __T.tutTip && __T.tutTip.key, __T.tutTip && __T.tutTip.text, document.getElementById('tut').dataset.pos, document.getElementById('tut').hidden]")
        async def wait(js, t=90000): await pg.wait_for_function(js, timeout=t, polling=150)
        await pg.goto('http://localhost:8765/pc_h.html', timeout=240000); await wait('typeof __T === "object"', 240000); await pg.wait_for_timeout(1500)
        print('lobby', await tip()); await shot('lobby')
        await pg.evaluate("document.getElementById('homePlay').click()"); await wait("__T.state === 'play'"); await wait("__T.tut && __T.tut.step === 0"); await pg.wait_for_timeout(600)
        print('move', await tip(), await pg.evaluate("[document.getElementById('slamBtn').hidden, document.getElementById('tutSlow').classList.contains('on'), __T.P.air]")); await shot('move')
        async def goto(sid, settle=900):
            await pg.evaluate("(() => { let n = 0; while (__T.tut && __T.TUT_STEPS[__T.tut.step].id !== '" + sid + "' && n++ < 20) __T.tutNext(); })()"); await pg.wait_for_timeout(settle)
        await goto('sling'); print('sling', await tip()); await shot('sling')
        await goto('basin'); print('basin', await tip(), await pg.evaluate("[+__T.P.paint.toFixed(2), document.getElementById('bar').className]")); await shot('basin')
        await goto('pound'); print('pound', await tip(), await pg.evaluate("[document.getElementById('slamBtn').hidden, __T.P.slamCD, +__T.P.paint.toFixed(2)]")); await shot('pound')
        await goto('dodge'); print('dodge', await tip(), await pg.evaluate("[__T.tut.drive === __T.H, __T.H.slamCD]")); await shot('dodge')
        await goto('item'); print('item', await tip(), await pg.evaluate("__T.powers.map(p => p.type)")); await shot('item')
        await goto('orb'); await wait("__T.orb.on", 60000); await pg.wait_for_timeout(600); print('orb', await tip(), await pg.evaluate("[__T.orb.on, +__T.orb.k.toFixed(2), document.getElementById('tutDim').classList.contains('on')]")); await shot('orb')
        await goto('rocketdodge', 1500); print('rocketdodge', await tip(), await pg.evaluate("[!!__T.H.rocket, __T.H.rocket && __T.H.rocket.ph, __T.orb.on]")); await shot('rocketdodge')
        await goto('flower', 1500); print('flower', await tip(), await pg.evaluate("[__T.gift && __T.gift.id, __T.gift && __T.gift.on, __T.orb.on]")); await shot('flower')
        await goto('rest'); print('rest', await tip(), await pg.evaluate("[__T.matchLeft, __T.P.kos, __T.tut.noTurret]")); await shot('rest')
        await pg.evaluate("__T.P.kos = 2; __T.matchLeft = 0.05;"); await wait("__T.state === 'dead'", 60000); await pg.wait_for_timeout(800)
        print('ended', await pg.evaluate("[__T.tutPh(), JSON.stringify(__T.store.tut), __T.store.drops, __T.endInfo && __T.endInfo.drops]"))
        await wait("!document.getElementById('tutWin').hidden", 60000); await pg.wait_for_timeout(2200); await shot('tutwin'); await pg.evaluate("document.getElementById('twNext').click()")
        await wait("!document.getElementById('victory').hidden", 90000); await pg.wait_for_timeout(2500); await pg.evaluate("document.getElementById('victory').click()")
        await wait("!document.getElementById('newItem').hidden", 60000); await pg.wait_for_timeout(2600); print('newitem', await tip()); await shot('newitem')
        await pg.evaluate("document.getElementById('niTry').click()"); await wait("__T.state === 'menu' && !document.getElementById('shop').hidden", 60000); await pg.wait_for_timeout(1200); print('shop', await tip()); await shot('shopflower')
        await pg.evaluate("document.getElementById('shopGrid').querySelector('.shitem[data-w=\"flower\"]').click()"); await pg.wait_for_timeout(1800); print('fangs', await tip(), await pg.evaluate("[__T.store.drops, JSON.stringify(__T.store.tut.price)]")); await shot('shopfangs')
        await pg.evaluate("document.getElementById('shopGrid').querySelector('.shitem[data-w=\"fangs\"]').click()"); await pg.wait_for_timeout(1800); print('bought', await tip(), await pg.evaluate("__T.store.drops")); await shot('shopback')
        await pg.evaluate("document.getElementById('shopBack').click()"); await pg.wait_for_timeout(1200); print('lobby2', await tip()); await shot('lobbylocker')
        await pg.evaluate("document.getElementById('lookBtn').click()"); await pg.wait_for_timeout(1500); print('locker', await tip()); await shot('lockerface')
        await pg.evaluate("document.getElementById('lc-face').click()"); await pg.wait_for_timeout(1200); print('face', await tip()); await shot('lockerfangs')
        await pg.evaluate("document.getElementById('lookRail').querySelector('.ltile[data-w=\"fangs\"]').click()"); await pg.wait_for_timeout(1200); print('worn', await tip(), await pg.evaluate("JSON.parse(localStorage.getItem('paint-world-red.v1')).look")); await shot('lockerdone')
        await pg.evaluate("document.getElementById('lookDone').click()"); await pg.wait_for_timeout(1500); print('pick', await tip()); await shot('pick')
        await pg.evaluate("document.getElementById('stageBtn').click()"); await pg.wait_for_timeout(1200); print('start', await tip()); await shot('start')
        await pg.evaluate("window.__instant = false; window.__noVote = false; window.__skipIntro = true; document.getElementById('startBtn').click()")
        await wait("!document.getElementById('vvote').hidden", 60000); await pg.wait_for_timeout(4000); await shot('vote')
        await wait("document.querySelector('#vts .vt.win')", 60000); print('votewin', await pg.evaluate("[document.querySelector('#vts .vt.win').dataset.s, document.getElementById('vvWin').textContent]")); await shot('votewin')
        await wait("__T.state === 'play'", 120000); print('match2', await pg.evaluate("[__T.tutPh(), __T.tut, __T.AI === undefined]"))
        await pg.evaluate("__T.P.kos = 2; __T.matchLeft = 0.05;"); await wait("__T.state === 'dead'", 60000); await pg.wait_for_timeout(500); print('done', await pg.evaluate("[__T.tutPh(), JSON.stringify(__T.store.tut)]"))
        print('errors', errs[:4]); await b.close()
k = sys.argv[1] if len(sys.argv) > 1 else 'port'
asyncio.run(main(*{'port': (390, 780, 'port'), 'land': (844, 390, 'land')}[k]))
