import asyncio, sys, json
from playwright.async_api import async_playwright
WS = '/tmp/claude-0/-home-user-rollmodel/5c52352e-692f-5301-ac55-ec4d2c708f3e/scratchpad/ws'
async def main(w, h, tag):
    async with async_playwright() as p:
        b = await p.chromium.launch(args=['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist'])
        ctx = await b.new_context(viewport={'width': w, 'height': h}, device_scale_factor=1, has_touch=True, is_mobile=True)
        await ctx.add_init_script("window.__tut = true; try { localStorage.setItem('paint-world-red.v1', JSON.stringify({ orient:'" + ('land' if w > h else 'port') + "', name:'Dusk', seen:{}, drops: 0 })); } catch (e) {}")
        pg = await ctx.new_page(); errs = []; pg.on('pageerror', lambda e: errs.append(str(e)[:300]))
        shots = []
        async def shot(name): await pg.screenshot(path=f'{WS}/ui/tut_{tag}_{name}.png'); shots.append(name)
        async def tip(): return await pg.evaluate("[__T.tutPh(), __T.tut && __T.tut.step, __T.tutTip && __T.tutTip.key, __T.tutTip && __T.tutTip.text, document.getElementById('tut').dataset.pos, document.getElementById('tut').hidden]")
        async def wait(js, t=90000): await pg.wait_for_function(js, timeout=t, polling=150)
        await pg.goto('http://localhost:8765/pc_h.html', timeout=240000); await wait('typeof __T === "object"', 240000); await pg.wait_for_timeout(1500)
        print('lobby', await tip()); await shot('lobby')
        await pg.evaluate("document.getElementById('homePlay').click()"); await wait("__T.state === 'play'"); await wait("__T.tut && __T.tut.step === 0"); await pg.wait_for_timeout(600)
        print('move', await tip(), await pg.evaluate("[document.getElementById('slamBtn').hidden, document.getElementById('tutSlow').classList.contains('on'), __T.P.air]")); await shot('move')
        async def goto(sid, settle=900):
            await pg.evaluate("(() => { let n = 0; while (__T.tut && __T.TUT_STEPS[__T.tut.step].id !== '" + sid + "' && n++ < 20) __T.tutNext(); })()"); await pg.wait_for_timeout(settle)
        await goto('sling'); print('sling', await tip()); await shot('sling')
        await pg.evaluate("__T.tutReward('move'); __T.tutReward('sling')"); await pg.wait_for_timeout(250); print('praise', await pg.evaluate("[document.getElementById('tutPraise').textContent, document.getElementById('tutPips').classList.contains('on'), [...document.querySelectorAll('#tutPips i.done')].length, __T.tut.bonus]")); await shot('praise')
        await goto('basin'); print('basin', await tip(), await pg.evaluate("[+__T.P.paint.toFixed(2), document.getElementById('bar').className]")); await shot('basin')
        await goto('pound'); d0 = await pg.evaluate("+Math.hypot(__T.H.x - __T.P.x, __T.H.z - __T.P.z).toFixed(1)"); await pg.wait_for_timeout(6000); print('pound', await tip(), await pg.evaluate("[document.getElementById('slamBtn').hidden, __T.P.slamCD, +__T.P.paint.toFixed(2), __T.tut.driveMode]"), 'rival dist', d0, '->', await pg.evaluate("+Math.hypot(__T.H.x - __T.P.x, __T.H.z - __T.P.z).toFixed(1)")); await shot('pound')
        await goto('dodge'); print('dodge', await tip(), await pg.evaluate("[__T.tut.drive === __T.H, __T.H.slamCD]")); await shot('dodge')
        await goto('item'); print('item', await tip(), await pg.evaluate("[__T.powers.map(p => [p.type, +p.y.toFixed(2), +Math.hypot(p.x - __T.P.x, p.z - __T.P.z).toFixed(1)]), document.getElementById('tutArrow').hidden]")); await shot('item')
        await goto('orb'); await wait("__T.orb.on", 60000); await pg.wait_for_timeout(600); print('orb', await tip(), await pg.evaluate("[__T.orb.on, +__T.orb.k.toFixed(2), document.getElementById('tutDim').classList.contains('on')]")); await shot('orb')
        await goto('rocketdodge', 1500); print('rocketdodge', await tip(), await pg.evaluate("[!!__T.H.rocket, __T.H.rocket && __T.H.rocket.ph, __T.orb.on]")); await shot('rocketdodge')
        await wait("__T.tut.rkFrozen || !__T.H.rocket", 120000); await pg.wait_for_timeout(300)
        print('rocketnow', await tip(), await pg.evaluate("[__T.tut.rkFrozen, __T.H.rocket && __T.H.rocket.ph, +(__T.H.y - __T.P.y).toFixed(1), +Math.hypot(__T.H.x - __T.P.x, __T.H.z - __T.P.z).toFixed(2), __T.tut.slowK]")); await shot('rocketnow')
        await pg.keyboard.press('Shift'); await wait("!__T.H.rocket", 120000); await pg.wait_for_timeout(400)
        print('rocketland', await pg.evaluate("[__T.P.st, __T.tut.rolled, __T.tut.hit, __T.TUT_STEPS[__T.tut.step].id]"))
        await goto('flower', 1000); print('flowerwait', await tip(), await pg.evaluate("[__T.gift.on, +__T.tut.wait.toFixed(2)]")); await wait('__T.gift.on', 30000); await pg.wait_for_timeout(1200); print('flower', await tip(), await pg.evaluate("[__T.gift && __T.gift.id, __T.gift && __T.gift.on, __T.orb.on, document.getElementById('tutArrow').hidden, document.getElementById('tutArrow').style.transform, document.getElementById('banner').classList.contains('on')]")); await shot('flower')
        await goto('rest'); await wait("!document.getElementById('tutGo').hidden", 60000); await pg.wait_for_timeout(700); t0 = await pg.evaluate("__T.runT")
        await pg.wait_for_timeout(1200); print('rest', await pg.evaluate("[__T.tut.card, __T.tut.slowK, +(__T.runT - " + str(t0) + ").toFixed(3), document.getElementById('tutSlow').classList.contains('on')]")); await shot('rest')
        await pg.evaluate("document.getElementById('tgGo').click()"); await pg.wait_for_timeout(1500); print('resumed', await pg.evaluate("[__T.tut.card, __T.tut.slowK, document.getElementById('tutGo').hidden, +__T.runT.toFixed(1)]"))
        await pg.evaluate("__T.P.kos = 2; __T.matchLeft = 0.05;"); await wait("__T.state === 'dead'", 60000); await pg.wait_for_timeout(800)
        print('ended', await pg.evaluate("[__T.tutPh(), JSON.stringify(__T.store.tut), __T.store.drops, __T.endInfo && __T.endInfo.drops]"))
        await wait("!document.getElementById('tutWin').hidden", 60000); await pg.wait_for_timeout(2600); print('tutwin', await pg.evaluate("document.getElementById('twRew').textContent")); await shot('tutwin'); await pg.evaluate("document.getElementById('twNext').click()")
        await wait("!document.getElementById('victory').hidden", 90000); await wait("__T.vic && __T.vic.t >= 1", 90000); await pg.evaluate("document.getElementById('victory').click()")
        await wait("!document.getElementById('newItem').hidden", 60000); await pg.wait_for_timeout(2600); print('newitem', await tip()); await shot('newitem')
        await pg.evaluate("document.getElementById('niTry').click()"); await wait("__T.state === 'menu' && !document.getElementById('shop').hidden", 60000); await pg.wait_for_timeout(1200); print('shop', await tip()); await shot('shopflower')
        await pg.evaluate("document.getElementById('shopGrid').querySelector('.shitem[data-w=\"flower\"]').click()"); await pg.wait_for_timeout(1800); print('fangs', await tip(), await pg.evaluate("[__T.store.drops, JSON.stringify(__T.store.tut.price)]")); await shot('shopfangs')
        await pg.evaluate("document.getElementById('shopGrid').querySelector('.shitem[data-w=\"fangs\"]').click()"); await pg.wait_for_timeout(1800); print('bought', await tip(), await pg.evaluate("__T.store.drops")); await shot('shopback')
        await pg.evaluate("document.getElementById('shopBack').click()"); await pg.wait_for_timeout(1200); print('lobby2', await tip()); await shot('lobbylocker')
        await pg.evaluate("document.getElementById('lookBtn').click()"); await pg.wait_for_timeout(1500); print('locker', await tip()); await shot('lockerface')
        await pg.evaluate("document.getElementById('lc-face').click()"); await pg.wait_for_timeout(1200); print('face', await tip()); await shot('lockerfangs')
        await pg.evaluate("document.getElementById('lookRail').querySelector('.ltile[data-w=\"fangs\"]').click()"); await pg.wait_for_timeout(1200); print('fangs on', await tip()); await shot('lockerhead')
        await pg.evaluate("document.getElementById('lc-head').click()"); await pg.wait_for_timeout(1200); print('head tab', await tip()); await shot('lockerflower')
        await pg.evaluate("document.getElementById('lookRail').querySelector('.ltile[data-w=\"flower\"]').click()"); await pg.wait_for_timeout(1200); print('worn', await tip(), await pg.evaluate("JSON.parse(localStorage.getItem('paint-world-red.v1')).look")); await shot('lockerdone')
        await pg.evaluate("document.getElementById('lookDone').click()"); await pg.wait_for_timeout(1500); print('pick', await tip()); await shot('pick')
        await pg.evaluate("document.getElementById('stageBtn').click()"); await pg.wait_for_timeout(1200); print('start', await tip(), await pg.evaluate("[document.getElementById('tutDim').className, document.getElementById('tutHand').hidden, __T.stageSel]")); await shot('start')
        b0 = await pg.evaluate("__T.stageSel"); await pg.mouse.click(370, 560); await pg.wait_for_timeout(900); print('picked', b0, '->', await pg.evaluate("__T.stageSel"))
        await pg.evaluate("window.__instant = false; window.__noVote = false; window.__skipIntro = false; document.getElementById('startBtn').click()")
        await wait("!document.getElementById('vvote').hidden", 60000); await pg.wait_for_timeout(4000); await shot('vote')
        await wait("document.querySelector('#vts .vt.win')", 60000); print('votewin', await pg.evaluate("[document.querySelector('#vts .vt.win').dataset.s, document.getElementById('vvWin').textContent]")); await shot('votewin')
        await wait("__T.state === 'play'", 300000); print('match2', await pg.evaluate("[__T.tutPh(), __T.tut, __T.AI === undefined]"))
        await pg.evaluate("__T.P.kos = 2; __T.matchLeft = 0.05;"); await wait("__T.state === 'dead'", 60000); await pg.wait_for_timeout(500); print('ended2', await pg.evaluate("[__T.tutPh(), JSON.stringify(__T.store.tut)]"))
        await wait("!document.getElementById('victory').hidden", 90000); await wait("__T.vic && __T.vic.t >= 1", 90000); await pg.evaluate("document.getElementById('victory').click()")
        await wait("!document.getElementById('end').hidden", 90000); await pg.wait_for_timeout(1500); print('end2', await tip()); await pg.evaluate("document.getElementById('menuBtn').click()")
        try: await wait("!document.getElementById('tutGo').hidden", 150000)
        except Exception: print('welcome diag', await pg.evaluate("[__T.tutPh(), __T.state, [...document.querySelectorAll('.modal:not([hidden]), section:not([hidden])')].map(e => e.id).join(','), __T.irisBusy, __T.lookOpen, document.getElementById('menu').dataset.page, document.getElementById('boot').className, document.getElementById('orient').hidden]")); raise
        await pg.wait_for_timeout(900); print('welcome', await pg.evaluate("[document.getElementById('tutGo').dataset.mode, document.getElementById('tgTitle').textContent, document.getElementById('commBtn').offsetParent === null]")); await shot('welcome')
        await pg.evaluate("document.getElementById('tgGo').click()"); await pg.wait_for_timeout(1200); print('done', await pg.evaluate("[__T.tutPh(), JSON.stringify(__T.store.tut), !document.getElementById('commModal').hidden, document.getElementById('commBtn').offsetParent !== null]")); await shot('comms')
        print('errors', errs[:4]); await b.close()
k = sys.argv[1] if len(sys.argv) > 1 else 'port'
asyncio.run(main(*{'port': (390, 780, 'port'), 'land': (844, 390, 'land')}[k]))
